/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Button} from 'react-native';
import Ipay88, {Pay} from 'react-native-ipay88';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };
  componentDidMount() {}
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Ipay88 example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Button
          title={'PAY'}
          onPress={() => {
            const data = {};
            data.paymentId = ''; // refer to ipay88 docs
            data.merchantKey = 'bTM5e8E2Ga';
            data.merchantCode = 'M06201';
            data.referenceNo = 'Z0200';
            data.amount = '2.30';
            data.currency = 'MYR';
            data.productDescription = 'Payment';
            data.userName = 'Angela';
            data.userEmail = 'angela@ipay.com';
            data.userContact = '60123456789';
            data.remark = 'cheap cheap';
            data.utfLang = 'UTF-8';
            data.country = 'MY';
            data.backendUrl =
              'https://isp-uat.api.axolot.app/payment/ipay88/callback';
            Pay(data);
          }}
        />
        <Ipay88
          successNotify={(data) => {
            console.log('OK');
          }}
          failedNotify={(data) => {
            console.log('NOK');
            console.log(data);
          }}
          cancelNotify={(data) => {
            console.log('CANCEL');
          }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
